# Generated by Django 5.2.1 on 2025-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_pet_last_interaction_pet_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
