# Generated by Django 5.2.1 on 2025-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', '貓'), ('dog', '狗'), ('rabbit', '兔子'), ('bird', '鳥')], default='cat', max_length=20),
        ),
    ]
